### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by FireEmerald** [jufabeck2202/LAI#20]
- [x] Darstellung mehrerer Tests.
- [x] Reload von Sub-Urls funktioniert nicht und gibt einen 404 error zurück.
- [x] Implementieren einer Hilfeseite

Export als Excel:
- [x] auf Nutzerbasis
- [x] auf Fragenbasis
- [x] Export an die Tabellen von Herrn Mandausch anpassen
und noch irgendwas anderes...

Charts:
- [x] ein paar Charts erstellen.
